version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: versions
          command: |
            node --version
            yarn --version
            npm --version

      - restore_cache:
          key: node-modules-cache-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          key: node-modules-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: yarn test